language: java

branches:
    only:
        - master
script:
- cd /home/travis/
- git clone https://github.com/Ortus-Solutions/cfdistro.git
- cd cfdistro
- ant
- cd /home/travis/build/Ortus-Solutions/regexpathinfofilter/build
- ant
- cd /home/travis/build/Ortus-Solutions/regexpathinfofilter
- ./releng build.compile
- ./releng build.jar
- ls
- mkdir dist/s3
- mv dist/localdev/regexpathinfofilter* dist/s3
deploy:
  # Upload binaries
  - provider: s3
    on:
      branch:
        - master
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: "downloads.ortussolutions.com"
    local-dir: dist/s3
    upload-dir: org/cfmlprojects/regexpathinfofilter/1.0.1
    acl: public_read